[package]
name = "apitest"
version = "0.1.0"
description = "ApiTest - desktop API debugger"
authors = ["ApiTest"]
edition = "2021"

[lib]
name = "apitest_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.32", features = ["bundled"] }
dirs = "5"
thiserror = "1"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "blocking", "multipart"] }
url = "2"
serde_yaml = "0.9"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
